name: Deploy to ECS 
on:
    push:
      branches:
        master
    workflow_dispatch:
jobs: 
    builddeploytoecs:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
        
          - name: checkout code 
            uses:  actions/checkout@v3
          - name: setup java and maven 
            uses:  actions/setup-java@v3
            with:
                distribution: 'adopt'
                java-version: '11' 
          - name: package with maven
            run:  mvn package
          - name: code analysis with sonarqube 
            run: mvn sonar:sonar -Dsonar.projectKey=xashy-web-app -Dsonar.host.url=${{secrets.SONAR_HOST_URL}} -Dsonar.token=${{secrets.SONAR_LOGIN_TOKEN}}
                #mvn sonar:sonar -Dsonar.projectKey=xashy-web-project -Dsonar.host.url=${{secrets.SONAR_HOST_URL}} -Dsonar.token=${{secrets.SONAR_LOGIN_TOKEN}}
          - name: upload to github packages
            run: mvn --batch-mode deploy
            env:
              GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} 
